# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gics', '0013_auto_20151217_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('default', "Contacter l'association"), ('president', 'Contacter le président (Didier Lesesvre)'), ('tresorier', 'Contacter le trésorier (Adrien Laroche)'), ('secretaire', 'Contacter le secrétaire (Antoine Houdard)'), ('atelier', 'Présenter un atelier'), ('respo paris6', 'Contacter le responsable Paris VI'), ('respo paris7', 'Contacter le responsable Paris VII'), ('respo paris13', 'Contacter le responsable Paris XIII'), ('respo telecom', 'Contacter le responsable Télécom Paris'), ('respo ulm', 'Contacter le responsable ENS Paris'), ('respo cachan', 'Contacter le responsable ENS Cachan'), ('respo x', 'Contacter le responsable École polytechnique'), ('respo orsay', 'Contacter le responsable Orsay'), ('webmaster', 'Contacter le webmaster (signaler un bug)')], default='default', max_length=32, verbose_name='Que souhaitez-vous faire ?')),
                ('name', models.CharField(max_length=128, verbose_name='Votre nom complet')),
                ('email', models.CharField(max_length=128, verbose_name='Votre mail')),
                ('message', models.TextField(verbose_name='Votre message')),
            ],
        ),
    ]
