# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gics', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('path', models.CharField(max_length=32)),
            ],
        ),
    ]
